# =====================================================
# Data displayed on the Home (About Me) page.
#
# 💡 Tip for Images / Logo:
# You can use either:
# 1. A full URL (e.g., https://example.com/logo.png)
# 2. A local file placed under /public/images/ and referenced with "/" (e.g., "/images/logo.png")
# =====================================================

# =====================================================
# 👤 Personal Information
# =====================================================

profile:
  name: "Youhui (Jeffrey) Wang"
  headline: "Undergraduate Student @ Harvard College | Cornell University"
  email: "jeffreywang0303 at cs dot stanford dot edu"
  location: Stanford, CA
  profileImage: "images/self.png"

  links:
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/youhuiwang/"
      icon:
        name: "FaLinkedin"
        package: "react-icons/fa6"

    - name: "Google Scholar"
      url: "https://scholar.google.com/citations?user=AtHsy-EAAAAJ&hl=zh-CN"
      icon:
        name: "FaGoogleScholar"
        package: "react-icons/fa6"

    - name: "Resume"
      url: "pdf/2:1:2026_Resume.pdf"
      icon:
        name: "FaRegIdBadge"
        package: "react-icons/fa6"

    - name: "CV"
      url: "pdf/2:1:2026_CV.pdf"
      icon:
        name: "FaFileLines"
        package: "react-icons/fa6"

    - name: "Github"
      url: "https://github.com/JeffreyWang060303"
      icon:
        name: "FaGithub"
        package: "react-icons/fa6"

  # you can use HTML syntax here (e.g. <br/>, <a>, <strong>, ...)
  biography: |
    Hi! I'm <strong>Jeffrey Wang</strong>, currently an Undergraduate Student at <strong>Cornell University</strong>, previously a visiting undergraduate scholar at <strong>Harvard College</strong>, passionate about <em>Robotics and Artificial Intelligence in general</em>.
    <div class="my-2"></div>
    Currently, I work as a <em>Research Intern</em> at the <strong>Stanford Vision and Learning Lab</strong>, fortunately advised by <strong>Dr. Huang Huang, Prof. Jiajun Wu, and Prof. Fei-fei Li</strong>, and <strong>Harvard Edge Computing Lab</strong>, fortunately advised by <strong>Jason Jabbour and Prof. Vijay Janapa Reddi</strong>.
    <div class="my-2"></div>
    <u>Research Interests:</u>
    <ul style="margin-top: 0.5rem; margin-bottom: 0.5rem; padding-left: 1.5rem;">
      <li>Robotic learning, perception, and control</li>
      <li>Embodied AI</li>
      <li>System Optimization</li>
    </ul>
    Outside of work, I enjoy <em>playing basketball, tennis, golf, ice hockey, squash, and traveling</em>, which inspire creativity and keep me energized. Feel free to connect to me for any potential opportunities or chatting!
# # =====================================================
# # 🎓 Education Section
# # =====================================================

education:
  - degree: "Computer Science, Visiting Undergraduate Student"
    school: "Harvard College"
    years: "2025 - 2026"
    logo: "images/harvard.png"
    logoDark: ""

  - degree: "B.S. in Information Science (Minors in Robotics and AI)"
    school: "Cornell University"
    years: "2023 - 2026"
    logo: "images/Cornell.png"
    logoDark: ""

# # =====================================================
# # 💼 Work Experience Section
# # =====================================================

workExperience:
  - title: "Research Intern"
    company: "Stanford Vision and Learning Lab, Stanford University"
    years: "Nov 2025 - Present"
    logo: "images/Stanford_Cardinal_logo.png"
    logoDark: ""

  - title: "Research Intern"
    company: "Institute for AI Industry Research (AIR), Tsinghua University"
    years: "May 2025 - August 2025"
    logo: "images/Tsinghua_University_Logo.png"
    logoDark: "images/Tsinghua_University_Logo-dark.png"

  - title: "Research Intern"
    company: "Charles Research Group, College of Engineering, Cornell University"
    years: "May 2024 - August 2024"
    logo: "images/cornelleng1.png"
    logoDark: "images/cornelleng1-dark.png"


# # =====================================================
# # 🛠️ Skills Section
# # =====================================================

skills:
  Programming:
    - name: "Python"
      logo: "images/python.svg"
      proficiency: Proficient
      description: null

    - name: "Java"
      logo: "images/java.svg"
      proficiency: Proficient
      description: null

    - name: "C/C++"
      logo: "images/cpp.svg"
      proficiency: Proficient
      description: null

    - name: "R"
      logo: "images/R.png"
      proficiency: Proficient
      description: null

    - name: "MATLAB"
      logo: "images/matlab.svg"
      proficiency: Advanced
      description: null

    - name: "Julia"
      logo: "images/julia.svg"
      proficiency: Advanced
      description: null

    - name: "Arduino"
      logo: "images/arduino.png"
      proficiency: Advanced
      description: null

    - name: "SQL"
      logo: "images/sql.png"
      proficiency: Advanced
      description: null

  Robotics/ML:
    - name: "PyTorch"
      logo: "images/pytorch.svg"
      proficiency: Proficient
      description: null

    - name: "Tensorflow"
      logo: "images/tensorflow.jpg"
      proficiency: proficient
      description: null

    - name: "ROS2"
      logo: "images/ros.png"
      proficiency: proficient
      description: null

    - name: "PyDrake"
      logo: "images/pydrake.png"
      proficiency: Advanced
      description: "MIT 6.4212: Robotic Manipulation"

    - name: "SOLIDWORKS"
      logo: "images/solidworks.png"
      proficiency: Advanced
      description: null


  Online Course Certificates:
    - name: "Deep Learning Specialization"
      logo: "images/coursera.svg"
      proficiency: Certified by DeepLearning.AI
      description: "January 2024"

    - name: "Machine Learning Specialization"
      logo: "images/coursera.svg"
      proficiency: Certified by DeepLearning.AI
      description: "September 2023"

    - name: "Python for Data Science, AI & Development"
      logo: "images/coursera.svg"
      proficiency: Certified by IBM
      description: "July 2023"


  Web Development:
    - name: "HTML"
      logo: "images/html.png"
      proficiency: Proficient
      description: null

    - name: "JavaScript"
      logo: "images/javascript.png"
      proficiency: Proficient
      description: null

    - name: "CSS"
      logo: "images/css.png"
      proficiency: Proficient
      description: null

  Language:
    - name: "English"
      logo: "images/language.svg"
      proficiency: Work Proficiency
      description: null

    - name: "Mandarin"
      logo: "images/language.svg"
      proficiency: Native
      description: null

    - name: "French"
      logo: "images/language.svg"
      proficiency: Advanced
      description: null
